In [2]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [3]:
# !pip install beautifulsoup4

In [4]:
url = 'https://www-fars.nhtsa.dot.gov/Main/index.aspx'
response = requests.get(url)
response

In [4]:
soup = BeautifulSoup(response.text)

table = soup.find('table', class_= 'datatable01')
rows = table.find_all('tr')
th = rows[0].find_all('th')
columns = [i.text for i in th]
columns
data = []
for tr in rows[1:]:
#     td = tr.find_all('td')
    row = [i.text for i in tr]
    data.append(row)

In [5]:
fars_df = pd.DataFrame(data, columns=columns).set_index('')

fars_df = fars_df.transpose()

In [6]:
fars_df

,Motor Vehicle Traffic Crashes,Fatal Crashes,Traffic Crash Fatalities,Vehicle Occupants,Drivers,Passengers,Unknown,Sub Total1,Motorcyclists,Nonmotorists,...,Other National Statistics,Vehicle Miles Traveled (Billions),Resident Population (Thousands),Registered Vehicles (Thousands),Licensed Drivers (Thousands),National Rates: Fatalities,Fatalities per 100 Million Vehicle Miles Traveled,"Fatalities per 100,000 Population","Fatalities per 100,000 Registered Vehicles","Fatalities per 100,000 Licensed Drivers"
2019*,,"33,244",,,"17,880","5,807",57,"23,744","5,014",,...,,"3,262","328,240","299,267","228,680",,1.11,11.00,12.06,15.78
2018,,"33,919",,,"18,321","5,962",49,"24,332","5,038",,...,,"3,240","326,688","297,036","227,558",,1.14,11.28,12.40,16.19
2017,,"34,560",,,"18,819","6,237",74,"25,130","5,226",,...,,"3,210","324,986","290,336","225,346",,1.17,11.53,12.91,16.63
2016,,"34,748",,,"18,717","6,485",74,"25,276","5,337",,...,,"3,174","322,941","288,034","221,712",,1.19,11.71,13.13,17.05
2015,,"32,538",,,"17,615","6,213",71,"23,899","5,029",,...,,"3,090","320,635","281,312","218,084",,1.15,11.07,12.61,16.27
2014,,"30,056",,,"16,470","5,766",71,"22,307","4,594",,...,,"3,020","318,301","274,805","214,092",,1.08,10.29,11.92,15.29
2013,,"30,202",,,"16,520","5,896",67,"22,483","4,692",,...,,"2,983","315,994","269,294","212,160",,1.10,10.41,12.21,15.50
2012,,"31,006",,,"16,838","6,106",73,"23,017","4,986",,...,,"2,963","313,831","265,647","211,815",,1.14,10.76,12.72,15.95
2011,,"29,867",,,"16,474","5,972",64,"22,510","4,630",,...,,"2,945","311,557","265,043","211,875",,1.10,10.42,12.25,15.33
2010,,"30,296",,,"16,864","6,451",56,"23,371","4,518",,...,,"2,967","309,322","257,312","210,115",,1.11,10.67,12.82,15.71
2009,,"30,862",,,"17,670","6,793",63,"24,526","4,469",,...,,"2,957","306,772","258,958","209,618",,1.15,11.05,13.08,16.16
2008,,"34,172",,,"19,279","7,441",71,"26,791","5,312",,...,,"2,977","304,094","259,360","208,321",,1.26,12.31,14.43,17.96
2007,,"37,435",,,"21,717","8,716",94,"30,527","5,174",,...,,"3,031","301,231","257,472","205,742",,1.36,13.70,16.02,20.05
2006,,"38,648",,,"22,831","9,187",101,"32,119","4,837",,...,,"3,014","298,380","251,415","202,810",,1.42,14.31,16.99,21.06
2005,,"39,252",,,"23,237","9,750",83,"33,070","4,576",,...,,"2,989","295,517","245,628","200,549",,1.46,14.72,17.71,21.70
2004,,"38,444",,,"23,158","10,042",76,"33,276","4,028",,...,,"2,965","292,805","237,949","198,889",,1.44,14.63,18.00,21.54
2003,,"38,477",,,"23,352","10,171",104,"33,627","3,714",,...,,"2,890","290,108","230,633","196,166",,1.48,14.78,18.59,21.86
2002,,"38,491",,,"23,625","10,370",110,"34,105","3,270",,...,,"2,856","287,625","225,685","194,602",,1.51,14.95,19.06,22.10
2001,,"37,862",,,"22,914","10,227",102,"33,243","3,197",,...,,"2,796","284,969","221,230","191,276",,1.51,14.81,19.07,22.06
2000,,"37,526",,,"22,914","10,451",86,"33,451","2,897",,...,,"2,747","282,162","217,028","190,625",,1.53,14.87,19.33,22.00
1999,,"37,140",,,"22,971","10,325",96,"33,392","2,483",,...,,"2,690","272,691","212,685","187,170",,1.55,15.30,19.61,22.29
1998,,"37,107",,,"22,654","10,327",107,"33,088","2,294",,...,,"2,628","270,248","208,076","184,861",,1.58,15.36,19.95,22.45
1997,,"37,324",,,"22,730","10,765",114,"33,609","2,116",,...,,"2,552","267,784","203,568","182,709",,1.65,15.69,20.64,22.99
1996,,"37,494",,,"22,572","10,860",102,"33,534","2,161",,...,,"2,484","265,229","201,631","179,539",,1.69,15.86,20.86,23.43
1995,,"37,241",,,"22,370","10,576",118,"33,064","2,227",,...,,"2,423","262,803","197,065","176,628",,1.73,15.91,21.22,23.68
1994,,"36,254",,,"21,596","10,294",108,"31,998","2,320",,...,,"2,358","260,327","192,497","175,403",,1.73,15.64,21.15,23.21

In [88]:
fars_df.iloc[0,0]

'\xa0 \xa0 \xa0'

In [91]:
fars_df.replace('\xa0 \xa0 \xa0', pd.NA, inplace= True)

In [95]:
fars_df.dropna(axis=1, inplace=True)

In [99]:
fars_df.rename('2019*', '2019')

TypeError: rename() takes from 1 to 2 positional arguments but 3 were given